# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "fw02"
  config.vm.network "private_network", ip: "10.100.100.253"
  config.vm.network "private_network", ip: "10.200.200.254" 
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt update
  SHELL


  # ==STDIN==
  # config.vm.provision "shell", inline: <<-SHELL
  #    apt install -y isc-dhcp-relay
  #    cat /vagrant/dhcp-relay/isc-dhcp-relay > /etc/default/isc-dhcp-relay
  #    systemctl restart isc-dhcp-relay
  #    systemctl status isc-dhcp-relay
  # SHELL


  # ==FIREWALL==
  config.vm.provision "shell", inline: <<-SHELL
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    
    cat /vagrant/iptables/iptables.fw02 > /usr/local/bin/adamo.sh
    chmod +x /usr/local/bin/adamo.sh

    cat /vagrant/iptables/adamo.service > /etc/systemd/system/adamo.service
    systemctl daemon-reload
    systemctl enable adamo
    systemctl start adamo
  SHELL

  # ==SSH==
  config.vm.provision "shell", inline: <<-SHELL
    useradd -m -s /bin/bash -p $(openssl passwd -1 "adamo") adamo
    cat /vagrant/ssh/banner > /etc/ssh/banner

    cat /vagrant/ssh/sshd_config > /etc/ssh/sshd_config

    systemctl restart sshd
  SHELL

  # ==NTP==
  config.vm.provision "shell", inline: <<-SHELL
    apt install -y chrony
    cat /vagrant/ntp/chrony.conf > /etc/chrony/chrony.conf
    systemctl restart chrony
  SHELL
end
